name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run markdown lint
        run: |
          npm install -g markdownlint-cli
          npm install -g remark-preset-lint-consistent
          npx remark . --use remark-preset-lint-consistent --frail
