name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run markdown linter
        run: |
          npm install -g markdownlint-cli
          npm install -g remark-preset-lint-consistent
          npm search remark-preset-lint-consistent --freal

      
